// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwSITa--w2H_0VrHQTTnD4XL_bu0HZ3Pc',
    appId: '1:227902974297:web:db8d93a28c1a6389648448',
    messagingSenderId: '227902974297',
    projectId: 'educonnect-8e2ed',
    authDomain: 'educonnect-8e2ed.firebaseapp.com',
    storageBucket: 'educonnect-8e2ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Dmo3KVZAbOl-5a9_KmylKFIK7Ol_eJA',
    appId: '1:227902974297:android:307312b967c3558b648448',
    messagingSenderId: '227902974297',
    projectId: 'educonnect-8e2ed',
    storageBucket: 'educonnect-8e2ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpdJND4AG5teQQW-U-9qCcx9QC3Zal-OY',
    appId: '1:227902974297:ios:3d2e975554d3480c648448',
    messagingSenderId: '227902974297',
    projectId: 'educonnect-8e2ed',
    storageBucket: 'educonnect-8e2ed.firebasestorage.app',
    iosBundleId: 'com.example.educonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpdJND4AG5teQQW-U-9qCcx9QC3Zal-OY',
    appId: '1:227902974297:ios:3d2e975554d3480c648448',
    messagingSenderId: '227902974297',
    projectId: 'educonnect-8e2ed',
    storageBucket: 'educonnect-8e2ed.firebasestorage.app',
    iosBundleId: 'com.example.educonnect',
  );
}
